# Generated by Django 5.0.6 on 2024-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_venta_alter_categoria_nombre_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='precio',
            new_name='precio_total',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
