# Generated by Django 5.0.6 on 2024-07-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='apellido_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
